### ISSUE TITLE
system tray pop up should follows shell theme

### ISSUE THREAD

**Issue by fikrillah** [hardpixel/unite-shell#108]
currently we have this

(strangely i cant take a screenshot of it, its a bug maybe? i dont know where to report)

but it would be nice if we have this: 

![Screenshot from 2019-04-24 15-40-49](https://user-images.githubusercontent.com/48489341/56646279-7631eb80-66a9-11e9-9ed3-d0eddcebd7e5.png)

the pic above is this extension https://extensions.gnome.org/extension/615/appindicator-support/ but it doesnt show all tray available, but for now im using it over the one unite extension provide simply because it looks better.

**Comment by jonian** [comment]
@fikrillah Thanks for the report. I'm closing this issue since it is not possible to interact with the menus created by the icons in the tray. Those menus are drawn by GTK/Qt or whatever framework the application uses.

The only way to have themed menus is the `appindicator` extension, which uses DBus to fetch the menu entries.
