### ISSUE TITLE
Top bar icons misaligned in the top bar

### ISSUE THREAD

**Issue by joselsegura** [hardpixel/unite-shell#147]
As you can see in the image attached bellow, some of the top bar icons (the ones normally aligned to the right corner) are displaces a few pixels down, placing them outside the top bar.
I have several extensions that are placing icons there, and I'm using "Hide Top Bar", but I have seen this behavior before I installed this one.
Please, tell me know if you need more info from my side to reproduce the problem or getting some log. I'm not an expert on JS but I can take a look and place any debug log wherever you want :-)

![gnome-shell-screenshot-EGDDB0](https://user-images.githubusercontent.com/1769148/69332767-a77e9400-0c57-11ea-9674-a9c8ebb2e75e.png)

Best regards

**Comment by drmikecrowe** [comment]
Please address this issue.  I've uninstalled until this is fixed

**Comment by jonian** [comment]
@JoseLSegura, @drmikecrowe I can't reproduce this. Is the issue still present in latest version?

**Comment by JoseLSegura** [comment]
@jonian apparently it isn't, at least for the latest version on extensions.gnome.org.

If you want more info, please tell me and I can look at what you need.

**Comment by jonian** [comment]
Thanks @JoseLSegura! Yes I was referring to the latest version on extensions.gnome.org.

**Comment by JoseLSegura** [comment]
During this days I updated Debian and the extensions, and the error is back again.

But I have some more information that could help; I have a dual monitor setup, my main "topbar" is in the left screen and I configured the "Auto Hide" to hide only when needed (for example, if there is no window on the left screen, the top bar is shown).

Given that setup, I noticed something:
- If I don't have any window on the left screen and the window on the right is screen is maximized, the **topbar is shown** and **unite icons are misaligned**
- If I don't have any window on the left screen and the window on the right is NOT maximized, the **topbar is shown** and **unite icons are aligned**
- If I have a maximized window on the left screen and I place the mouse near to the top (in order to the topbar to be shown), the **unite icons are misaligned**
- If I have a NOT maximized window on the left screen and I place the window near to the top bar, it is hidden. If I place the mouse near to the topbar in order to show it, the **unite icons are aligned**.

So, I guess that maximizing windows is changing "something" that makes unite icons to be misaligned with the topbar, and it doesn't matter if the topbar is visible or not.

Maybe it is a bit of a mess, so I can record a screencast to share my experience if you want.

**Comment by JoseLSegura** [comment]
@jonian IDK how to reopen the issue (probably I don't have permissions on your repo). Please feel free to reopen it or, if you want, I can create a new one.

**Comment by jonian** [comment]
@JoseLSegura What gnome-shell/debian version are you on?  
I have dropped support for gnome-shell < 3.32

**Comment by JoseLSegura** [comment]
Debian Unstable, Shell 3.36 (3.36.1-5 deb version)

**Comment by jonian** [comment]
> I have a dual monitor setup, my main "topbar" is in the left screen and I configured the "Auto Hide"

What extension are you using for that?   
Is the issue present if you disable that extension?

**Comment by JoseLSegura** [comment]
I'm using https://extensions.gnome.org/extension/545/hide-top-bar/

And apparently, yes.

I have the topbar on the left screen and if I maximize the window on any of the two screens, the topbar icons become misaligned.

I just discover one more thing: if I have only one of the two windows maximized, when I put the focus on the non-maximized, the icons go to their position, but if I switch to the maximized window, the icons are moved a few pixels to the bottom and become misaligned.

And another thing: in addition to the misalignment on the Y-axis, the spacing between elements on the topbar change too (it is increased at the same time the icons are misaligned)

**Comment by JoseLSegura** [comment]
New finding:

If I disable "Show window buttons in top bar" (previously configured as "Maximized"), the problem goes away.

This is indifferent if I enable or not the Hide topbar extensions

**Comment by jonian** [comment]
Thanks for the reports @JoseLSegura. Can you share a screencast with the issue? It will be easier to try to reproduce it.

**Comment by JoseLSegura** [comment]
@jonian https://photos.app.goo.gl/URroF6rRWDA8C6zY6
