### ISSUE TITLE
Bug with telegram app bar 

### ISSUE THREAD

**Issue by hotmule** [hardpixel/unite-shell#161]
![image](https://user-images.githubusercontent.com/37577810/77818372-d8c60f80-70e2-11ea-9889-3f05fe40b13d.png)
After some open-close window actions app bar moves under top panel, maximize and minimize buttons are hiding and window becomes not resizable

**Comment by siegfriedhuber** [comment]
I see the same behaviour in Clementine and Double Commander.

**Comment by jonian** [comment]
I have been able to reproduce this only with Qt applications and the issue is with get motif hints (needed to prevent double decorations in apps like firefox/chrome):

https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/window.js#L62

@siegfriedhuber is Double Commander a Qt or a GTK application?

**Comment by siegfriedhuber** [comment]
Hi. Here's the version information for Double Commander:

Double Commander
Version: 0.9.6 beta
Revision: 9018
Build date: 2019/09/05
Lazarus: 2.0.2.0
FPC: 3.0.4
Platform: x86_64-Linux-qt5
OS version: Ubuntu 19.10

Widgetset library: Qt 5.12.4, libQt5Pas 5.6.1

**Comment by siegfriedhuber** [comment]
And so is Clementine. It also uses Qt version 5.12.4.
