### ISSUE TITLE
Status Menu icons cluttered when enabling User Themes extension alongside Unite

### ISSUE THREAD

**Issue by Magean0** [hardpixel/unite-shell#182]
Hey,

I've noticed an odd behaviour, which occurs on GNOME 3.36 (Ubuntu 20.04) when doing the following:

1. Enable Unite and User Themes extensions simultaneously. No need to enable any custom theme: default Adwaita will do. 
2. Log off then back in.
3. See how the Status Menu [looks cluttered now](https://imgur.com/jXKoOci), as if spacing between each icon had been reduced to 0.

Hovering over the Status Menu fixes the glitch.

I've run `journalctl /usr/bin/gnome-shell | grep unite` but there's no output (fresh install).

Of course the bug could be on User Themes' part.

Cheers, Unite really is a must-have on the GNOME desktop.

**Comment by jonian** [comment]
Hi @Magean0, thanks for the detailed report.

I'm not able to reproduce this on GNOME 3.36 (Arch Linux) as with #163. Maybe the issue is only present on Ubuntu.

> I've run journalctl /usr/bin/gnome-shell | grep unite but there's no output (fresh install).

You won't find anything in the logs about this because it does not happen due to an error.

As you can see [here](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/layout.js#L230), the extension uses a workaround to fix an issue on gnome-shell reported [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1708), so I don't think I can do anything else to fix this, sorry.
