### ISSUE TITLE
[Dash to Panel] Top bar window buttons position "Last" is not last anymore since v38

### ISSUE THREAD

**Issue by thomas-wach** [hardpixel/unite-shell#189]
Top bar window buttons are now placed into "right" bar, not last bar anymore.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/Fm9d4f5/screen.png" alt="screen" border="0"></a>

Arch-Linux
GNOME Shell 3.36.4
Linux evolution-01 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux

**Comment by esa1975** [comment]
Not sure why but I'm running 3.36.4 on Arch and this works fine. Is there a conflict with another extension by any chance?

**Comment by thomas-wach** [comment]
Yep, sorry I didn't test that prior ...

When I deactivate dash-to-panel, behaviour is correct again.

"Right" and "Last" (should be most right) aren't honored correctly with dash-to-panel activated.
"Last" is used in the same manner as "Right".

I'll open same ticket in dash-to-panel.
Let's see, whom is able to solve it.

**Comment by thomas-wach** [comment]
Further discussed [https://github.com/home-sweet-gnome/dash-to-panel/issues/1091#issuecomment-667665631](https://github.com/home-sweet-gnome/dash-to-panel/issues/1091#issuecomment-667665631)

**Comment by thomas-wach** [comment]
If we could exactly define the box (right, system-date, system-menu, center, etc) where the window-buttons shall appear, dash-to-panel wouldn't have to change aynthing, I think.

**Comment by jonian** [comment]
> If we could exactly define the box (right, system-date, system-menu, center, even better desktop-button etc)

@thomas-wach, without Dash to Panel installed the only available boxes to place the buttons are left, center and right. 

System-date, system-menu etc. are originally placed inside those 3 boxes. DtP creates its own box and move system-date, system-menu etc. outside the left, center and right boxes.

In order to support what you are proposing, unite has to check for the existence of DtP and provide slots available only in DtP. That will be error prone and I'm against implementing it.

What can be done is DtP, since it moves the widgets already, to allow moving all widgets in top panel that are added using `Main.panel.addToStatusArea` and are available in `Main.panel.statusArea`.

Widgets added by unite are uniteDesktopLabel, uniteTrayIndicator, uniteWindowControls.
