### ISSUE TITLE
[Feature Request] Use GTK theme buttons instead of custom buttons

### ISSUE THREAD

**Issue by ghost** [hardpixel/unite-shell#50]
I create a working extension here, just for test it:
https://github.com/lestcape/metacity-buttons

I open also a question in stackoverflow related with that, to find a better implementation if some one help:
https://stackoverflow.com/questions/50313744/how-to-darwing-the-window-buttons-from-a-gtk-context-in-gjs

Whatever you want to know about it, just ask.

**Comment by lapega** [comment]
Your github site is down. Can you post another link? I'm really interested in use the current theme buttons with this extension.

**Comment by jonian** [comment]
@lapega https://gitlab.com/lestcape/metacity-buttons

**Comment by vekat** [comment]
this would make it work with yaru/communitheme, I think it's a great idea

**Comment by jonian** [comment]
@vekat Right now it is easier and less complicated to add the yaru buttons theme, than to implement the metacity-buttons extension.

In the future I'm planning to implement this, since it is a better solution so you can use a custom theme or inherit from the gtk theme.

**Comment by jonian** [comment]
@lestcape Thanks. I will add this feature in an upcoming version.

**Comment by lestcape** [comment]
I hope the problem of Gjs can also be resolved to not need to instantiate a gtk components just for nothing, but in the meantime, it should work using the gtk instances.

> In the future I'm planning to implement this, since it is a better solution so you can use a custom theme or inherit from the gtk theme.

Yes is nice in that way, because if some theme fail for some reason you can load the custom version. Also i think that could be possible extract the buttons for an specific installed Gtk theme, not matter if is the current applied theme or not. So, users could change between the custom extension themes, all real installed Gtk themes and the current applied Gtk theme. Of course. it will need something to scan for current installed themes. In cinnamon, this python function load the available themes: https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py#L268
