### ISSUE TITLE
Right click on title of maximized window should show context menu

### ISSUE THREAD

**Issue by hurrycaner** [hardpixel/unite-shell#60]
When my window is maximized and i've set it to show title on top panel, would be nice to show context menu when right clicking at window title, today it only shows the option to exit, would be nice to have all default options, so i could send it to another workspace without the need of unmaximizing window :)

**Comment by ubone** [comment]
or add Minimize and Unmaximize to the app-menu [on left click]
for windows without CSDs which normally only have Quit

**Comment by jonian** [comment]
Hi @ubone, thank you for your input.

Showing the context menu looks easier (less code) than adding menu entries to the app menu and as @hurrycaner reported, being able to move the window to another workspace is now impossible without unmaximizing the window.

Is there any specific use-case for you suggestion that I did not understand?

**Comment by ubone** [comment]
it's intuitive, not sure which extension did it, either maximus or 'no title bar',
but only for those with the simple app menu

My thinking is, for the windows with complex title bars - do nothing (as gnome default),
for the windows with simple title bar - hide close button and title and have min unmax where Quit is

sort of related but could the close [min/max] button not be removed from title bar with options in it?
(since it's not removed anyway) when the option 'show window buttons in the top bar' is not used

think i should open another thread as feature request suggestion for this to not off topic here
